# Generated by Django 4.2 on 2023-04-06 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
